name: Build & Publish UBI Podman Image

on:
  workflow_dispatch:
  schedule:
    - cron: "35 3 * * *" # WINTER (CST): 9:35PM  Summer (CDT): 10:35PM
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-image.yaml"
      - "ubi.containerfile"

env:
  DISTRO_VERSION: 9
  CONTAINERFILE: ubi.containerfile

# Reference: https://github.com/nzwulfin/cicd-bootc/blob/main/.github/workflows/build_fedora_bootc.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, linux]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: lint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ${{ env.CONTAINERFILE }}

  build:
    name: Build UBI Podman Image
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, linux]
    container:
      image: registry.access.redhat.com/ubi9/ubi
      # Volume mount to workaround for https://github.com/redhat-actions/podman-login/issues/42 since the docker config from the host doesn't come up to the container
      options: --privileged -v /github/home/.docker/:/github/home/.docker/:rw
    needs: lint
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone the repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get container tools in UBI builder
        run: dnf -y install jq podman podman-docker buildah skopeo

      # Replacing redhat-actions/podman-login
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Upstream UBI Image
        run: podman pull registry.access.redhat.com/ubi${{ env.DISTRO_VERSION}}/ubi:latest

      - name: Inspect Image and Expose Labels
        id: image_labels
        run: |
          podman image inspect registry.access.redhat.com/ubi${{ env.DISTRO_VERSION }}/ubi:latest | \
          jq -r '.[0].Labels | to_entries[] | "\(.key | gsub("[.-]"; "_"))=\(.value)"' >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Container Image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          # Tags: latest ${{ steps.image_labels.outputs.version }} ${{ steps.image_labels.outputs.release }} YYMMDD SHA
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=v${{ steps.image_labels.outputs.version }},enable={{is_default_branch}}
            type=raw,value=r${{ steps.image_labels.outputs.release }},enable={{is_default_branch}}
            type=schedule,pattern={{date 'YYYYMMDD' tz='America/Chicago'}},enable={{is_default_branch}}
            type=sha

      # Replacing redhat-actions/buildah-build and use the `docker format` to support the SHELL instruction.
      - name: Build Image with Buildah
        id: build-image
        run: |
          # 1. Extract the primary tag
          PRIMARY_TAG=$(echo '${{ steps.meta.outputs.json }}' | jq -r '.tags[0]')

          # 2. Build the image with docker format
          buildah bud \
            --format docker \
            --build-arg DISTRO_VERSION=${{ env.DISTRO_VERSION }} \
            --file ${{ env.CONTAINERFILE }} \
            --tag "$PRIMARY_TAG" .

          # 3. Apply the remaining tags
          for TAG in $(echo '${{ steps.meta.outputs.json }}' | jq -r '.tags[]'); do
            buildah tag "$PRIMARY_TAG" "$TAG"
          done

      # Replacing redhat-actions/push-to-registry
      - name: Push to GHCR
        run: |
          # Use the JSON output to iterate cleanly
          for TAG in $(echo '${{ steps.meta.outputs.json }}' | jq -r '.tags[]'); do
            echo "Pushing $TAG..."
            buildah push "$TAG"
          done
